-- ============================================================
-- Migration 00008: Cognitive Tests & Skills Assessment
-- ============================================================

-- 1. Cognitive test sessions
create type cognitive_test_category as enum (
  'logique', 'math', 'verbal', 'spatial', 'mixte'
);

create type cognitive_test_status as enum (
  'in_progress', 'completed', 'abandoned', 'timeout'
);

create table public.cognitive_test_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  category cognitive_test_category not null,
  difficulty public.difficulty_level not null default 'intermediaire',
  status cognitive_test_status not null default 'in_progress',
  score int,
  max_score int,
  question_count int not null default 10,
  time_limit_minutes int not null default 15,
  time_spent_seconds int,
  current_question int not null default 0,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create index idx_cognitive_test_sessions_user on public.cognitive_test_sessions(user_id);

-- 3. Cognitive test questions (generated by AI, stored for history)
create table public.cognitive_test_questions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.cognitive_test_sessions(id) on delete cascade,
  question_text text not null,
  options jsonb not null,
  correct_index int not null,
  user_answer_index int,
  is_correct boolean,
  explanation text,
  difficulty public.difficulty_level not null default 'intermediaire',
  points int not null default 1,
  order_num int not null,
  created_at timestamptz not null default now()
);

create index idx_cognitive_test_questions_session on public.cognitive_test_questions(session_id);

-- 4. Skills assessment categories
create table public.skills_assessment_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  icon text,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 5. Skills assessment questions (predefined)
create table public.skills_assessment_questions (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.skills_assessment_categories(id) on delete cascade,
  question_text text not null,
  order_num int not null default 0,
  weight int not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index idx_saq_category on public.skills_assessment_questions(category_id);

-- 6. Skills assessment sessions
create type skills_assessment_status as enum (
  'draft', 'in_progress', 'completed'
);

create table public.skills_assessments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  status skills_assessment_status not null default 'draft',
  overall_score int,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index idx_skills_assessments_user on public.skills_assessments(user_id);

-- 7. Skills assessment answers
create table public.skills_assessment_answers (
  id uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references public.skills_assessments(id) on delete cascade,
  question_id uuid not null references public.skills_assessment_questions(id) on delete cascade,
  rating int not null check (rating >= 1 and rating <= 5),
  created_at timestamptz not null default now(),
  unique (assessment_id, question_id)
);

-- 8. Skills assessment results (AI-generated report)
create table public.skills_assessment_results (
  id uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references public.skills_assessments(id) on delete cascade unique,
  category_scores jsonb not null,
  global_summary text,
  strengths jsonb,
  areas_for_improvement jsonb,
  training_gap_analysis jsonb,
  generated_at timestamptz not null default now()
);

-- ============================================================
-- 9. Link training_recommendations to skills_assessments
-- (must be after skills_assessments table creation)
-- ============================================================

alter table public.training_recommendations
  alter column session_id drop not null;

alter table public.training_recommendations
  add column if not exists assessment_id uuid references public.skills_assessments(id) on delete cascade;

create index if not exists idx_training_recommendations_assessment
  on public.training_recommendations(assessment_id);

-- ============================================================
-- SEED DATA: 5 assessment categories + 25 questions
-- ============================================================

insert into public.skills_assessment_categories (name, description, icon, display_order) values
  ('Technique', 'Compétences techniques liées à votre domaine professionnel', 'IconCode', 1),
  ('Bureautique', 'Maîtrise des outils bureautiques (Excel, Word, PowerPoint, etc.)', 'IconFileDescription', 2),
  ('Langues', 'Niveau en langues étrangères', 'IconLanguage', 3),
  ('Management', 'Capacités d''encadrement, de gestion d''équipe et de projet', 'IconUsers', 4),
  ('Soft Skills', 'Compétences comportementales et relationnelles', 'IconHeart', 5);

insert into public.skills_assessment_questions (category_id, question_text, order_num, weight) values
  -- Technique (5 questions)
  ((select id from public.skills_assessment_categories where name = 'Technique'), 'Maîtrise des langages de programmation', 1, 2),
  ((select id from public.skills_assessment_categories where name = 'Technique'), 'Connaissance des architectures logicielles', 2, 2),
  ((select id from public.skills_assessment_categories where name = 'Technique'), 'Capacité à résoudre des problèmes complexes', 3, 2),
  ((select id from public.skills_assessment_categories where name = 'Technique'), 'Veille technologique et apprentissage continu', 4, 1),
  ((select id from public.skills_assessment_categories where name = 'Technique'), 'Maîtrise des outils de versioning (Git, etc.)', 5, 1),
  -- Bureautique (5 questions)
  ((select id from public.skills_assessment_categories where name = 'Bureautique'), 'Maîtrise d''Excel (tableaux, formules, TCD)', 1, 2),
  ((select id from public.skills_assessment_categories where name = 'Bureautique'), 'Maîtrise de Word (mise en page, publipostage)', 2, 1),
  ((select id from public.skills_assessment_categories where name = 'Bureautique'), 'Maîtrise de PowerPoint (présentations professionnelles)', 3, 1),
  ((select id from public.skills_assessment_categories where name = 'Bureautique'), 'Utilisation des outils collaboratifs (Teams, Slack, Notion)', 4, 1),
  ((select id from public.skills_assessment_categories where name = 'Bureautique'), 'Gestion de documents et archivage numérique', 5, 1),
  -- Langues (5 questions)
  ((select id from public.skills_assessment_categories where name = 'Langues'), 'Niveau en français (écrit et oral)', 1, 2),
  ((select id from public.skills_assessment_categories where name = 'Langues'), 'Niveau en anglais professionnel', 2, 2),
  ((select id from public.skills_assessment_categories where name = 'Langues'), 'Capacité à rédiger des documents professionnels', 3, 1),
  ((select id from public.skills_assessment_categories where name = 'Langues'), 'Aisance à l''oral en contexte professionnel', 4, 1),
  ((select id from public.skills_assessment_categories where name = 'Langues'), 'Compréhension de documents techniques en anglais', 5, 1),
  -- Management (5 questions)
  ((select id from public.skills_assessment_categories where name = 'Management'), 'Animation et leadership d''équipe', 1, 2),
  ((select id from public.skills_assessment_categories where name = 'Management'), 'Gestion de projet et méthodologies (Agile, Scrum)', 2, 2),
  ((select id from public.skills_assessment_categories where name = 'Management'), 'Prise de décision et résolution de conflits', 3, 2),
  ((select id from public.skills_assessment_categories where name = 'Management'), 'Délégation et suivi des performances', 4, 1),
  ((select id from public.skills_assessment_categories where name = 'Management'), 'Gestion budgétaire et reporting', 5, 1),
  -- Soft Skills (5 questions)
  ((select id from public.skills_assessment_categories where name = 'Soft Skills'), 'Communication interpersonnelle', 1, 2),
  ((select id from public.skills_assessment_categories where name = 'Soft Skills'), 'Adaptabilité et gestion du changement', 2, 2),
  ((select id from public.skills_assessment_categories where name = 'Soft Skills'), 'Travail en équipe et collaboration', 3, 1),
  ((select id from public.skills_assessment_categories where name = 'Soft Skills'), 'Autonomie et initiative', 4, 1),
  ((select id from public.skills_assessment_categories where name = 'Soft Skills'), 'Gestion du stress et des priorités', 5, 2);

-- ============================================================
-- RLS POLICIES
-- ============================================================

alter table public.cognitive_test_sessions enable row level security;
alter table public.cognitive_test_questions enable row level security;
alter table public.skills_assessment_categories enable row level security;
alter table public.skills_assessment_questions enable row level security;
alter table public.skills_assessments enable row level security;
alter table public.skills_assessment_answers enable row level security;
alter table public.skills_assessment_results enable row level security;

-- Cognitive tests: users see their own sessions
create policy "Users read own test sessions"
  on public.cognitive_test_sessions for select
  using (auth.uid() = user_id);

create policy "Users insert own test sessions"
  on public.cognitive_test_sessions for insert
  with check (auth.uid() = user_id);

create policy "Users update own test sessions"
  on public.cognitive_test_sessions for update
  using (auth.uid() = user_id);

-- Test questions: read if own session
create policy "Users read own test questions"
  on public.cognitive_test_questions for select
  using (exists (
    select 1 from public.cognitive_test_sessions s
    where s.id = session_id and s.user_id = auth.uid()
  ));

create policy "System insert test questions"
  on public.cognitive_test_questions for insert
  with check (exists (
    select 1 from public.cognitive_test_sessions s
    where s.id = session_id and s.user_id = auth.uid()
  ));

-- Skills categories/questions: public read
create policy "Anyone read categories"
  on public.skills_assessment_categories for select
  using (true);

create policy "Anyone read questions"
  on public.skills_assessment_questions for select
  using (true);

-- Skills assessments: user owns their own
create policy "Users read own assessments"
  on public.skills_assessments for select
  using (auth.uid() = user_id);

create policy "Users insert own assessments"
  on public.skills_assessments for insert
  with check (auth.uid() = user_id);

create policy "Users update own assessments"
  on public.skills_assessments for update
  using (auth.uid() = user_id);

-- Answers: own assessment
create policy "Users manage own answers"
  on public.skills_assessment_answers for all
  using (exists (
    select 1 from public.skills_assessments a
    where a.id = assessment_id and a.user_id = auth.uid()
  ));

-- Results: own assessment
create policy "Users read own results"
  on public.skills_assessment_results for select
  using (exists (
    select 1 from public.skills_assessments a
    where a.id = assessment_id and a.user_id = auth.uid()
  ));

create policy "System insert results"
  on public.skills_assessment_results for insert
  with check (exists (
    select 1 from public.skills_assessments a
    where a.id = assessment_id and a.user_id = auth.uid()
  ));
